In [1]:
import numpy as np

print('numpy를 이용한 다차원 배열 계산')

print('1차원 배열의 예시')
A = np.array([1, 2, 3, 4])
print('전체 배열 >>' + str(A))
print('배열의 차수 >>' + str(np.ndim(A)))
print('배열의 형상 >>' + str(A.shape))
print('배열 원소의 형상 >>' + str(A.shape[0]))
print('--------------------------------------')

numpy를 이용한 다차원 배열 계산
1차원 배열의 예시
전체 배열 >>[1 2 3 4]
배열의 차수 >>1
배열의 형상 >>(4,)
배열 원소의 형상 >>4


In [2]:
print('2차원 배열의 예시')
B = np.array([[1, 2], [3, 4],[5, 6]])
print('전체 배열 >>' + str(B))
print('배열의 차수 >>' + str(np.ndim(B)))
print('배열의 형상 >>' + str(B.shape))
print('--------------------------------------')

2차원 배열의 예시
전체 배열 >>[[1 2]
 [3 4]
 [5 6]]
배열의 차수 >>2
배열의 형상 >>(3, 2)


In [4]:
print('행렬의 내적 예시')
A = np.array([[1, 2], [3, 4]])
print('배열의 형상 >>' + str(A.shape))
B = np.array([[5, 6], [7, 8]])
print('배열의 형상 >>' + str(B.shape))

print('두 행렬의 내적을 넘파이 함수 np.dot()을 이용해서 계산')
print(np.dot(A, B))
print('--------------------------------------')

행렬의 내적 예시
배열의 형상 >>(2, 2)
배열의 형상 >>(2, 2)
두 행렬의 내적을 넘파이 함수 np.dot()을 이용해서 계산
[[19 22]
 [43 50]]
--------------------------------------


In [6]:
print('다차원일때 행렬의 내적 예시')
A = np.array([[1, 2], [3, 4],[5, 6]])
print('배열의 형상 >>' + str(A.shape))
B = np.array([7, 8])
print('배열의 형상 >>' + str(B.shape))

print('두 행렬의 내적을 넘파이 함수 np.dot()을 이용해서 계산')
print(np.dot(A, B))
print('--------------------------------------')

다차원일때 행렬의 내적 예시
배열의 형상 >>(3, 2)
배열의 형상 >>(2,)
두 행렬의 내적을 넘파이 함수 np.dot()을 이용해서 계산
[23 53 83]
--------------------------------------


In [10]:
print('신경망의 내적 예시')
X = np.array([1, 2])
print(X)
print(X.shape)
W = np.array([[1, 3, 5],[2, 4, 6]])
print(W)
print(W.shape)
Y = np.dot(X, W)
print('신경망의 내적 예시 결과 >>' + str(Y))

신경망의 내적 예시
[1 2]
(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
신경망의 내적 예시 결과 >>[ 5 11 17]
